
version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    user: root
    volumes:
      - ./prometheus:/prometheus
      - prometheus-data:/data
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
    depends_on:
      - alertmanager
    ports:
      - 9090:9090
    restart: always
  
  alertmanager:
    image: prom/alertmanager
    user: root
    restart: always
    volumes:
      - ./alertmanager:/alertmanager
      - alertmanager-data:/data
    command:
      - '--config.file=/alertmanager/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093
  
  alertmanager-bot:
    image: metalmatze/alertmanager-bot:0.4.2
    restart: always
    command:
    - --log.level=info
    - --store=bolt
    - --bolt.path=/data/bot.db
    environment:
      ALERTMANAGER_URL: http://alertmanager:9093
      TELEGRAM_ADMIN: xxx
      TELEGRAM_TOKEN: xxx
    depends_on:
      - alertmanager
    volumes:
    - alertmanager-bot-data:/data
  
  blackbox_exporter:
    image: prom/blackbox-exporter
    ports:
      - 9115:9115
    dns: 8.8.8.8
    restart: always
    volumes:
      - "./blackbox:/blackbox"
    command: --config.file=/blackbox/blackbox.yml

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-provisioning:/etc/grafana/provisioning/

  cadvisor:
    image: google/cadvisor:latest
    restart: always
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg:/dev/kmsg

volumes:
  prometheus-data:
  alertmanager-data:
  grafana-data:
  grafana-provisioning:
  alertmanager-bot-data:
