
version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    user: root
    volumes:
      - ./prometheus:/prometheus
      - prometheus-data:/data
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
    ports:
      - 9090:9090
    restart: always
  
  grafana:
    restart: always
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-provisioning:/etc/grafana/provisioning/

  cadvisor:
    image: google/cadvisor:latest
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/snap/docker/common/var-lib-docker/:/var/lib/docker:ro

volumes:
  prometheus-data:
  grafana-data:
  grafana-provisioning: