version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    user: root
    volumes:
      - ./prometheus:/prometheus
      - prometheus-data:/data
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/data'
    depends_on:
      - alertmanager
    ports:
      - 9090:9090
    networks:
      - core
  
  alertmanager:
    image: prom/alertmanager
    user: root
    restart: always
    volumes:
      - ./alertmanager:/alertmanager
      - alertmanager-data:/data
    command:
      - '--config.file=/alertmanager/alertmanager.yml'
      - '--storage.path=/data'
    ports:
      - 9093:9093
    networks:
      - core

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-provisioning:/etc/grafana/provisioning/
    networks:
      - core

volumes:
  prometheus-data:
  alertmanager-data:
  grafana-data:
  grafana-provisioning:

networks:
  core:
    external: true
