global:
  scrape_interval: 45s 
  evaluation_interval: 45s 

  external_labels:
    monitor: codelab
    environment: Production
    service: Prometheus
    region: EU
    dc: eu-west-1

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
- job_name: 'prometheus'
  static_configs:
          - targets: ['prometheus:9090']

- job_name: 'node'
  static_configs:
    # gluteus and pfsense are given host name by dhcp
    - targets: ['gluteus.owodunni.home:9100']

- job_name: eth-node
  metrics_path: /debug/metrics/prometheus
  scheme: http
  static_configs:
  - targets:
    - eth-node:6060
