global:
  scrape_interval: 45s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 45s # Evaluate rules every 15 seconds. The default is every 1 minute.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
- job_name: 'prometheus'
  static_configs:
          - targets: ['prometheus:9090', cadvisor:8080]

- job_name: 'node'
  static_configs:
    - targets: ['192.168.1.119:9100', '192.168.1.220:9100']