version: '3.2'

services:
  agent:
    image: portainer/agent
    restart: always
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network

  portainer:
    image: portainer/portainer-ce
    restart: always
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      - 9000:9000
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    depends_on:
      - agent

networks:
  agent_network:

volumes:
  portainer_data: